version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./api/.env
    command: npm run start:dev
    depends_on:
      - frontend

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
